receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    verbosity: detailed
  otlphttp:
    endpoint: "http://otel_backend:8000"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, otlphttp]
    traces:
      receivers: [otlp]
      exporters: [logging, otlphttp]
    logs:
      receivers: [otlp]
      exporters: [logging, otlphttp]
